# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39a923bf9d34a2a104e32e568dd1e95aafb2390bf3143f8c09e37624af1764f647f1d6a746b7d5884feef6a331a5f245ffead076f84aa2810042b0866a308737

test:
  secret_key_base: 640879521eab9a62a968dfec93d2431b3da034564b943e46b18dc3e2244f308f0862c313cfb81458ad79e85b28d4afe06c868cf83a3bef2bdeb3f643757b8e33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
